import type { Listing } from "./types";

// Demo listings shown until Supabase is connected (see README).
// Images are cute placeholder illustrations in /public/items — replace
// with real photos via the admin panel once Supabase is set up.
export const SEED_LISTINGS: Listing[] = [
  {
    id: "seed-1",
    name: "Milkmaid Puff-Sleeve Top",
    description:
      "Cream square-neck milkmaid top with puff sleeves. Worn twice, no flaws. So soft and pinterest-coded.",
    price: 12,
    condition: "Like new",
    size: "S",
    category: "tops",
    seller: "cherrelle",
    status: "available",
    image: "/items/top-1.svg",
    images: ["/items/top-1.svg"],
    created_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "seed-2",
    name: "Floral Tiered Midi Dress",
    description:
      "Dusty pink floral midi with tiered skirt and smocked back. Tiny pull near hem (pictured) — barely noticeable.",
    price: 22,
    condition: "Lightly worn",
    size: "M",
    category: "dresses",
    seller: "karina",
    status: "available",
    image: "/items/dress-1.svg",
    images: ["/items/dress-1.svg"],
    created_at: "2026-06-02T10:00:00Z",
  },
  {
    id: "seed-3",
    name: "Ribbon-Tie Cardigan",
    description:
      "Blush knit cardigan with ribbon ties. Brand new, bought the wrong size. Original tag attached.",
    price: 18,
    condition: "Brand new with tag",
    size: "M",
    category: "tops",
    seller: "anthea",
    status: "reserved",
    image: "/items/top-2.svg",
    images: ["/items/top-2.svg"],
    created_at: "2026-06-03T10:00:00Z",
  },
  {
    id: "seed-4",
    name: "High-Waist Wide-Leg Trousers",
    description:
      "Ivory wide-leg trousers, high waisted with side zip. Hemmed for ~158cm. No flaws.",
    price: 15,
    condition: "Lightly worn",
    size: "S",
    category: "bottoms",
    seller: "selena",
    status: "available",
    image: "/items/bottom-1.svg",
    images: ["/items/bottom-1.svg"],
    created_at: "2026-06-04T10:00:00Z",
  },
  {
    id: "seed-5",
    name: "Pearl Bow Hair Clips (Set of 3)",
    description:
      "Set of three pearl and ribbon bow clips. Worn once for a shoot. Comes with organza pouch.",
    price: 6,
    condition: "Like new",
    size: "Free size",
    category: "accessories",
    seller: "charlotte",
    status: "available",
    image: "/items/acc-1.svg",
    images: ["/items/acc-1.svg"],
    created_at: "2026-06-05T10:00:00Z",
  },
  {
    id: "seed-6",
    name: "Linen A-Line Mini Skirt",
    description:
      "Soft white linen-blend mini with built-in shorts. Belt loop slightly loose — stated as-is.",
    price: 10,
    condition: "Well loved",
    size: "S",
    category: "bottoms",
    seller: "cherrelle",
    status: "sold",
    image: "/items/bottom-2.svg",
    images: ["/items/bottom-2.svg"],
    created_at: "2026-06-05T12:00:00Z",
  },
  {
    id: "seed-7",
    name: "Satin Slip Dress in Rose",
    description:
      "Dusty rose satin slip dress with adjustable straps. Dry-cleaned, ready for a new home.",
    price: 25,
    condition: "Like new",
    size: "M",
    category: "dresses",
    seller: "selena",
    status: "available",
    image: "/items/dress-2.svg",
    images: ["/items/dress-2.svg"],
    created_at: "2026-06-06T10:00:00Z",
  },
  {
    id: "seed-8",
    name: "Quilted Mini Shoulder Bag",
    description:
      "Cream quilted bag with gold-tone chain. Light scuff on base (pictured). Fits phone + cardholder + lip balm.",
    price: 14,
    condition: "Lightly worn",
    size: "Free size",
    category: "accessories",
    seller: "karina",
    status: "available",
    image: "/items/acc-2.svg",
    images: ["/items/acc-2.svg"],
    created_at: "2026-06-07T10:00:00Z",
  },
  {
    id: "seed-9",
    name: "Lace-Trim Camisole",
    description:
      "White lace-trim cami, double lined. Bought from a local boutique, worn once.",
    price: 9,
    condition: "Like new",
    size: "XS",
    category: "tops",
    seller: "charlotte",
    status: "reserved",
    image: "/items/top-3.svg",
    images: ["/items/top-3.svg"],
    created_at: "2026-06-08T10:00:00Z",
  },
  {
    id: "seed-10",
    name: "Coquette Ribbon Belt",
    description:
      "Skinny blush ribbon belt with heart buckle. New without tag — never found an outfit for it.",
    price: 5,
    condition: "Brand new without tag",
    size: "Free size",
    category: "accessories",
    seller: "anthea",
    status: "available",
    image: "/items/acc-3.svg",
    images: ["/items/acc-3.svg"],
    created_at: "2026-06-09T10:00:00Z",
  },
];
